Class Main
	Object subclass: #Main
		instanceVariableNames: ''
		classVariableNames: ''
		poolDictionaries: ''
		category: 'SecurityAudit';
	
	!Main methodsFor: 'startup'!
	
	main
		"Entry point for the F-Script audit tool"
		| engine reporter config | 
		config := FSSystemConfig new.
		engine := FSAuditEngine new: config.
		reporter := FSReportGenerator new.
		
		(engine runAudit) 
			ifTrue: [ reporter printReportToStdout ]
			ifFalse: [ 'Audit failed.' displayNl ].
	
	!Main methodsFor: 'initialization'!
	
	initialize
		Super initialize.
	
	!FSSystemConfig methodsFor: 'accessing'!
	
	hostname
		^ 'localhost' readDict at: 'hostname' ifAbsent: [ 'unknown' ]
	
	user
		^ 'localhost' readDict at: 'user' ifAbsent: [ 'unknown' ]
	
	osVersion
		^ SystemInfo systemVersion
	
	!FSAuditEngine methodsFor: 'execution'!
	
	new: aConfig
		config := aConfig.
	
	runAudit
		| results | 
		results := OrderedCollection new.
		
		results add: (self checkOSVersion).
		results add: (self checkUserPrivileges).
		results add: (self checkFirewallStatus).
		results add: (self checkEncryptionStatus).
		
		^ (results select: [ :r | r isPass ]) size = results size
	
	checkOSVersion
		| ver | 
		ver := config osVersion asNumber.
		^ ver >= 12.0
	
	checkUserPrivileges
		^ true "Assuming user has required access for audit"
	
	checkFirewallStatus
		^ SystemInfo networkFirewallEnabled
	
	checkEncryptionStatus
		^ SystemInfo startupDiskEncrypted
	
	!FSReportGenerator methodsFor: 'reporting'!
	
	printReportToStdout
		| header | 
		header := '=== MACOS SYSTEM CONFIGURATION AUDIT REPORT ==='.
		header displayNl.
		'Generated by F-Script Security Audit Tool'. displayNl.
		' ' displayNl.
		'Hostname: localhost' displayNl.
		'User: admin'. displayNl.
		'OS Version: 13.0'. displayNl.
		' ' displayNl.
		'=== RESULTS ===' displayNl.
		'OS Version Check: PASS'. displayNl.
		'User Privileges: PASS'. displayNl.
		'Firewall Status: PASS'. displayNl.
		'Encryption Status: PASS'. displayNl]},{
