-- PL/SQL Compliance Framework: Database Schema Setup

-- Drop existing objects for clean setup (optional in production)
BEGIN
  FOR rec IN (SELECT object_name, object_type FROM user_objects WHERE object_name LIKE 'CPM_%') LOOP
    EXECUTE IMMEDIATE 'DROP ' || rec.object_type || ' ' || rec.object_name || ' FORCE';
  END LOOP;
END;
/ 

-- Policy Definitions Table
CREATE TABLE cpm_policies (
  policy_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  policy_name    VARCHAR2(100) NOT NULL UNIQUE,
  policy_version NUMBER NOT NULL DEFAULT 1,
  rule_description CLOB NOT NULL,
  severity_level VARCHAR2(20) NOT NULL, -- LOW, MEDIUM, HIGH, CRITICAL
  is_active      NUMBER(1) DEFAULT 1,
  created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Audit Log Table
CREATE TABLE cpm_audit_log (
  log_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type     VARCHAR2(50) NOT NULL,
  policy_id      NUMBER,
  component      VARCHAR2(100),
  status         VARCHAR2(20), -- PASS, FAIL, INFO
  details        CLOB,
  created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_policy FOREIGN KEY (policy_id) REFERENCES cpm_policies(policy_id)
);

-- Drift History Table
CREATE TABLE cpm_drift_history (
  drift_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  policy_id      NUMBER,
  baseline_value VARCHAR2(4000),
  current_value  VARCHAR2(4000),
  drift_type     VARCHAR2(50), -- CONFIG_CHANGE, PERMISSION_CHANGE, etc.
  detected_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_drift_policy FOREIGN KEY (policy_id) REFERENCES cpm_policies(policy_id)
);

-- Remediation Table
CREATE TABLE cpm_remediation (
  remediation_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  policy_id      NUMBER,
  action_type    VARCHAR2(100),
  action_script  CLOB,
  status         VARCHAR2(20) DEFAULT 'PENDING', -- PENDING, IN_PROGRESS, COMPLETED, FAILED
  created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_rem_policy FOREIGN KEY (policy_id) REFERENCES cpm_policies(policy_id)
);

-- Policy Index
CREATE INDEX idx_policy_name ON cpm_policies(policy_name);
CREATE INDEX idx_audit_log_event ON cpm_audit_log(event_type);
CREATE INDEX idx_drift_policy ON cpm_drift_history(policy_id);
