% TOKEN_SPEC: Hardware Security Token Manufacturing Specification
; This file contains the standardized specifications for hardware token fabrication
; Used to validate G-code generation parameters

; [IDENTIFICATION]
TOKEN_ID=HST-SEC-001
MANUFACTURING_BATCH=2024-A
AUDIT_TRAIL_REQUIRED=YES

; [DIMENSIONS]
WIDTH=35.0
DEPTH=20.0
THICKNESS=2.5
TOLERANCE=±0.05

; [GEOMETRY]
SHAPE=RECTANGULAR_WITH_FILLETS
FILLET_RADIUS=10.0
HOLE_PATTERNS=4
HOLE_DIAMETER=1.5
HOLE_DEPTH=3.0
KEY_INDENTATION=YES

; [MATERIAL_SPEC]
MATERIAL=STAINLESS_STEEL_316L
SURFACE_FINISH=Ra_0.8
ANTI_FINGERPRINT_COATING=YES
MAGNETIC_PROPERTIES=NON_MAGNETIC

; [SECURITY_FEATURES]
ENCRYPTED_CHANNEL_INDENTATION=YES
NFC_COIL_SLOT_DEPTH=1.2
NFC_COIL_SLOT_WIDTH=8.0
RFID_TAG_SLOT_DEPTH=0.5
RFID_TAG_SLOT_WIDTH=10.0

; [MACHINING_REQUIREMENTS]
SPINDLE_SPEED_RPM=20000
FEED_RATE_MM_PER_MIN=300
PLUNGE_RATE_MM_PER_MIN=80
COOLANT_TYPE=SYNTHETIC_OIL
TOOL_CHANGES=3
INSPECTION_POINTS=12

; [COMPLIANCE]
STANDARD=ISO_10303
CERTIFICATION_LEVEL=2
CHAIN_OF_CUSTODY=REQUIRED

% END_SPEC
