# System Baseline Configuration
# Key=Value

kernel.panic=10
net.ipv4.ip_forward=0
net.ipv4.conf.all.rp_filter=1
net.ipv4.tcp_syncookies=1
fs.suid_dumpable=0
vm.swappiness=10
user.max_user_namespaces=62832
