*******************************************************************************;
* report_generator.sas - Output Generation Module;
*******************************************************************************;

%macro generate_compliance_report();
    ods html file="&out_dir.compliance_report.html" style=styles.printer;
    
    proc print data=work.non_compliant_entities label noobs;
        title 'Enterprise Security Compliance Status';
        title2 'Generated by SAS Security Compliance Analyzer';
        var user severity_norm policy_violated total_risk compliance_status;
        where policy_violated = 1;
    run;
    
    proc freq data=work.non_compliant_entities;
        tables compliance_status;
        title 'Compliance Distribution Summary';
    run;
    
    ods html close;
    
    /* Export to SAS Dataset for downstream systems */
    proc datasets lib=work nolist;
        delete anomaly_scores baseline_stats compliance_checks flagged_users non_compliant_entities;
    quit;
%mend;
