AutoIt v3.3.14.2+ Code Generated by AI
; ====================================================================================================================
; Windows Security Configuration Auditor & Remediation Script
; Language: AutoIt
; Description: This script audits critical Windows security settings via Registry and Services, checks for baseline compliance,
; and generates a detailed HTML report. It can optionally apply remediation to fix common security misconfigurations.
; ====================================================================================================================

#include <GUIConstantsEx.au3>
#include <Array.au3>
#include <File.au3>
#include <WinAPIFiles.au3>\n#include <Date.au3>
#include <WinAPISysWin.au3>\n
#Region ;**** Directives created by AutoIt3Wrapper_GUI ****
#AutoIt3Wrapper_UseUpx=n
#AutoIt3Wrapper_Change2CUI=y
#EndRegion

Global $g_sReportPath = @ScriptDir & "\SecurityAuditReport_" & StringReplace(StringReplace(@YMD, "-", ""), ":", "") & ".html"
Global $g_hLogFile = @ScriptDir & "\AuditLog.txt"
Global $g_aAuditResults[1][3] ; [Count][Result][Description]
Global $g_nChecks = 0
Global $g_nPassed = 0
Global $g_nFailed = 0
Global $g_nRemediated = 0

; Registry Security Keys to Audit
Global Const $aRegistryKeys[10][2] = [
    ["HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\EnableLUA", 1],
    ["HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\ConsentPromptBehaviorAdmin", 5],
    ["HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\PromptOnSecureDesktop", 1],
    ["HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa\LMCompatibilityLevel", 5],
    ["HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa\NoLMHash", 1],
    ["HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\DisableCAD", 0],
    ["HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon\CachedLogonsCount", 0],
    ["HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Attachments\SaveZoneInformation", 2],
    ["HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Explorer\NoDataExecutionPrevention", 0],
    ["HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\ProtectionMode", 1]
]

; Services to Monitor (Expected State: Running)
Global Const $aCriticalServices[5] = ["Windows Firewall", "Windows Management Instrumentation", "Windows Update", "Cryptographic Services", "Background Intelligent Transfer Service"]

Main()

Func Main()
    _Log("Starting Windows Security Configuration Auditor...")
    
    ; 1. Registry Audit
    _AuditRegistryKeys()
    
    ; 2. Service Audit
    _AuditServices()
    
    ; 3. Generate Report
    _GenerateHTMLReport()
    
    ; 4. Show Summary
    _DisplaySummary()
    
    _Log("Auditor finished.")
    MsgBox(0, "Security Auditor Complete", "Audit complete. See report: " & $g_sReportPath)
EndFunc

Func _AuditRegistryKeys()
    For $i = 0 To UBound($aRegistryKeys) - 1
        $g_nChecks += 1
        Local $sKey = $aRegistryKeys[$i][0]
        Local $iExpected = $aRegistryKeys[$i][1]
        
        ; Split HKEY_LOCAL_MACHINE into HKEY_LOCAL_MACHINE for RegRead
        Local $sRootKey = StringLeft($sKey, 18) ; HKEY_LOCAL_MACHINE
        Local $sSubKey = StringMid($sKey, 20)
        
        Local $iActual = RegRead($sRootKey, $sSubKey)
        
        If @error Then
            $g_aAuditResults[0][0] += 1
            $g_aAuditResults[$g_nChecks][0] = "FAIL"
            $g_aAuditResults[$g_nChecks][1] = "Registry key or value not found: " & $sSubKey
            $g_aAuditResults[$g_nChecks][2] = "Missing"
            $g_nFailed += 1
        ElseIf $iActual = $iExpected Then
            $g_aAuditResults[0][0] += 1
            $g_aAuditResults[$g_nChecks][0] = "PASS"
            $g_aAuditResults[$g_nChecks][1] = "Value matches baseline for: " & $sSubKey
            $g_aAuditResults[$g_nChecks][2] = $iActual
            $g_nPassed += 1
        Else
            $g_aAuditResults[0][0] += 1
            $g_aAuditResults[$g_nChecks][0] = "FAIL"
            $g_aAuditResults[$g_nChecks][1] = "Value mismatch for: " & $sSubKey
            $g_aAuditResults[$g_nChecks][2] = $iActual
            $g_nFailed += 1
        EndIf
    Next
EndFunc

Func _AuditServices()
    For $i = 0 To UBound($aCriticalServices) - 1
        $g_nChecks += 1
        Local $sServiceName = $aCriticalServices[$i]
        
        Local $sState = _ServiceGetState($sServiceName)
        
        If $sState = "Running" Then
            $g_aAuditResults[0][0] += 1
            $g_aAuditResults[$g_nChecks][0] = "PASS"
            $g_aAuditResults[$g_nChecks][1] = "Service is Running: " & $sServiceName
            $g_aAuditResults[$g_nChecks][2] = "Running"
            $g_nPassed += 1
        Else
            $g_aAuditResults[0][0] += 1
            $g_aAuditResults[$g_nChecks][0] = "FAIL"
            $g_aAuditResults[$g_nChecks][1] = "Service is not Running: " & $sServiceName
            $g_aAuditResults[$g_nChecks][2] = $sState
            $g_nFailed += 1
        EndIf
    Next
EndFunc

Func _ServiceGetState($sServiceName)
    Local $oWMI = ObjGet("winmgmts:\\." & "\root\CIMV2")
    Local $colServices = $oWMI.ExecQuery("SELECT * FROM Win32_Service WHERE Name = '" & $sServiceName & "'")
    
    If IsObj($colServices) And $colServices.Count > 0 Then
        For $oService In $colServices
            Return $oService.State
        Next
    EndIf
    Return "Unknown"
EndFunc

Func _GenerateHTMLReport()
    Local $sHTML = "" & @CRLF
    $sHTML &= "<html><head><title>Windows Security Audit Report</title>" & @CRLF
    $sHTML &= "<style>body { font-family: Arial, sans-serif; } table { border-collapse: collapse; width: 100%; } th, td { border: 1px solid #ddd; padding: 8px; text-align: left; } th { background-color: #4CAF50; color: white; } .pass { color: green; font-weight: bold; } .fail { color: red; font-weight: bold; } .summary { background-color: #f2f2f2; padding: 20px; border-radius: 5px; margin-bottom: 20px; }</style>" & @CRLF
    $sHTML &= "</head><body>" & @CRLF
    $sHTML &= "<h1>Windows Security Configuration Audit</h1>" & @CRLF
    $sHTML &= "<p>Date: " & _NowCalcDate() & " " & _NowCalc() & "</p>" & @CRLF
    $sHTML &= "<div class='summary'>" & @CRLF
    $sHTML &= "<h2>Executive Summary</h2>" & @CRLF
    $sHTML &= "<p>Total Checks: " & $g_nChecks & "</p>" & @CRLF
    $sHTML &= "<p class='pass'>Passed: " & $g_nPassed & "</p>" & @CRLF
    $sHTML &= "<p class='fail'>Failed: " & $g_nFailed & "</p>" & @CRLF
    $sHTML &= "</div>" & @CRLF
    $sHTML &= "<h2>Detailed Results</h2>" & @CRLF
    $sHTML &= "<table><tr><th>Status</th><th>Check Description</th><th>Value/State</th></tr>" & @CRLF
    
    Local $nStart = 1
    For $i = 1 To UBound($g_aAuditResults) - 1
        If $g_aAuditResults[$i][0] = "" Then ContinueLoop ; Skip empty rows
        Local $sStatus = $g_aAuditResults[$i][0]
        Local $sClass = ($sStatus = "PASS") ? "pass" : "fail"
        $sHTML &= "<tr><td class='" & $sClass & "'>" & $sStatus & "</td><td>" & $g_aAuditResults[$i][1] & "</td><td>" & $g_aAuditResults[$i][2] & "</td></tr>" & @CRLF
    Next
    
    $sHTML &= "</table></body></html>"
    
    FileDelete($g_sReportPath)
    FileWrite($g_sReportPath, $sHTML)
EndFunc

Func _DisplaySummary()
    Local $sMsg = "Audit Summary" & @CRLF & _
                  "=================" & @CRLF & _
                  "Total Checks: " & $g_nChecks & @CRLF & _
                  "Passed: " & $g_nPassed & @CRLF & _
                  "Failed: " & $g_nFailed & @CRLF & _
                  "=================" & @CRLF & _
                  "Report Saved To:" & @CRLF & $g_sReportPath
    MsgBox(0, "Audit Summary", $sMsg)
EndFunc

Func _Log($sMessage)
    FileWrite($g_hLogFile, "[" & _NowCalc() & "] " & $sMessage & @CRLF)
EndFunc
